services:
  db:
    image: postgres:16-alpine
    container_name: ft_checkmate_db
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d ft_checkmate"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ft_checkmate_frontend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      db:
        condition: service_healthy

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: ft_checkmate_nginx
    restart: unless-stopped
    ports:
      - "443:443"
    depends_on:
      - frontend
  adminer:
    image: adminer
    container_name: ft_checkmate_adminer
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
volumes:
  postgres_data:
