// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
export default {
  datasource: {
    url: "env:DATABASE_URL",
  },
  schema: "prisma/schema.prisma", // adapte si ton schema est ailleurs
};
